import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html data-theme="dark" lang="en">
            {/* <html lang="en"> */}
            <body className={inter.className}>
                {" "}
                <NextAuthProvider>
                    {/* <TwitterNavbar /> */}
                    {children}
                </NextAuthProvider>
            </body>
        </html>
    );
}
